version: 2

models:
  - name: stg_customers
    description: "Staging table for customer data cleaned from RAW.CUSTOMERS"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: first_name
        description: "Customer first name"

      - name: last_name
        description: "Customer last name"

      - name: email
        description: "Customer email address"

      - name: city
        description: "Customer city"

      - name: state
        description: "Customer state"

      - name: country
        description: "Customer country"

      - name: status
        description: "Customer status (ACTIVE / INACTIVE)"

      - name: updated_at
        description: "Timestamp when customer record was last updated"

  - name: stg_orders
    description: "Staging table for order header data from RAW.ORDERS"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique

      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null

      - name: store_id
        description: "Store where the order was placed"
        tests:
          - not_null

      - name: order_date
        description: "Date when the order was created"

      - name: order_status
        description: "Order status (DELIVERED / CANCELLED)"

  - name: stg_order_items
    description: "Staging table for order line items from RAW.ORDER_ITEMS"
    columns:
      - name: order_item_id
        description: "Unique identifier for each order line item"
        tests:
          - not_null
          - unique

      - name: order_id
        description: "Associated order identifier"
        tests:
          - not_null

      - name: product_id
        description: "Product associated with the order item"
        tests:
          - not_null

      - name: quantity
        description: "Quantity ordered"

      - name: discount_pct
        description: "Discount percentage applied"

  - name: stg_products
    description: "Staging table for product master data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - not_null
          - unique

      - name: product_name
        description: "Product name"

      - name: category
        description: "Product category"

      - name: subcategory
        description: "Product sub-category"

      - name: unit_price
        description: "Price per unit of product"

  - name: stg_stores
    description: "Staging table for store master data"
    columns:
      - name: store_id
        description: "Unique store identifier"
        tests:
          - not_null
          - unique

      - name: store_name
        description: "Store name"

      - name: city
        description: "Store city"

      - name: region
        description: "Business region of the store"
